// <auto-generated />
using System;
using DoctorWho.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorWho.Db.Migrations
{
    [DbContext(typeof(DoctorWhoCoreDbContext))]
    [Migration("20210901065755_addCreatedAtAndMofifiedAtPropsToSchemas")]
    partial class addCreatedAtAndMofifiedAtPropsToSchemas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorWho.Db.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Suhaib Hamdallah",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 667, DateTimeKind.Local).AddTicks(8199),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(6895)
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Anas Zakarneh",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(7958),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(7974)
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mohammad Abu-Qasedo",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(7995),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(7998)
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Stephen Hillenburg",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8001),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8004)
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Craig McCracken",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8007),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8010)
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Genndy Tartakovsky",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8014),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8017)
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Alex Hirsch",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8020),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8022)
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Butch Hartman",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8025),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 670, DateTimeKind.Local).AddTicks(8029)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Companion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WhoPlayed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanionName = "Zaid Nour",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(8901),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(8927)
                        },
                        new
                        {
                            Id = 2,
                            CompanionName = "Jweid Hamdallah",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9573),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9586)
                        },
                        new
                        {
                            Id = 3,
                            CompanionName = "Amjad Salhab",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9605),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9608)
                        },
                        new
                        {
                            Id = 4,
                            CompanionName = "Osaid Nour",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9611),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9614)
                        },
                        new
                        {
                            Id = 5,
                            CompanionName = "Yazan Fouqha",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9617),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9620)
                        },
                        new
                        {
                            Id = 6,
                            CompanionName = "Osaid Hamdallah",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9623),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9626)
                        },
                        new
                        {
                            Id = 7,
                            CompanionName = "Hasan Khalaf",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9629),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9632)
                        },
                        new
                        {
                            Id = 8,
                            CompanionName = "Rayan Hamdallah",
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9635),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 671, DateTimeKind.Local).AddTicks(9638)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BithDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DoctorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstEpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(407),
                            DoctorName = "Dr. William A. Abdu, M.D, M.S.",
                            DoctorNumber = 1,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(422)
                        },
                        new
                        {
                            Id = 2,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1531),
                            DoctorName = "Dr. Myles. B. Abbott, M.D.",
                            DoctorNumber = 2,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1545)
                        },
                        new
                        {
                            Id = 3,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1584),
                            DoctorName = "Dr. Khalid Abbed, M.D.",
                            DoctorNumber = 3,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1587)
                        },
                        new
                        {
                            Id = 4,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1591),
                            DoctorName = "Dr. Fouad. M. Abbas, M.D.",
                            DoctorNumber = 4,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1594)
                        },
                        new
                        {
                            Id = 5,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1598),
                            DoctorName = "Dr. Naresh Trehan",
                            DoctorNumber = 5,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1601)
                        },
                        new
                        {
                            Id = 6,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1604),
                            DoctorName = "Dr. Ahmad Assi",
                            DoctorNumber = 6,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1607)
                        },
                        new
                        {
                            Id = 7,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1611),
                            DoctorName = "Dr. Laith Sharaqa",
                            DoctorNumber = 7,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1614)
                        },
                        new
                        {
                            Id = 8,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1618),
                            DoctorName = "Dr. Hamza Nour",
                            DoctorNumber = 8,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(1620)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1800)
                        .HasColumnType("nvarchar(1800)");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Enemies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(2373),
                            Description = "bla bla",
                            EnemyName = "Eric Cartman",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(2388)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3161),
                            Description = "bla bla",
                            EnemyName = "Vicky",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3174)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3208),
                            Description = "bla bla",
                            EnemyName = "Stewie Griffin",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3211)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3214),
                            Description = "bla bla",
                            EnemyName = "Maleficent",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3217)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3220),
                            Description = "bla bla",
                            EnemyName = "Mr. Pickles ",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3223)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3226),
                            Description = "bla bla",
                            EnemyName = "Ahmad Nassar",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3229)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3232),
                            Description = "bla bla",
                            EnemyName = "Mohammad Domidi",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3235)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3238),
                            Description = "bla bla",
                            EnemyName = "Ammar Omar",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3241)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EpisodeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1800)
                        .HasColumnType("nvarchar(1800)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3971),
                            DoctorId = 1,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 1",
                            EpisodeType = "TYPE 1",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(3986),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6307),
                            DoctorId = 2,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 2",
                            EpisodeType = "TYPE 2",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6322),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6393),
                            DoctorId = 3,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 3",
                            EpisodeType = "TYPE 3",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6396),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6401),
                            DoctorId = 4,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 4",
                            EpisodeType = "TYPE 3",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6404),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6408),
                            DoctorId = 5,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 5",
                            EpisodeType = "TYPE 2",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6411),
                            SeriesNumber = 2
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6415),
                            DoctorId = 6,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 6",
                            EpisodeType = "TYPE 1",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6418),
                            SeriesNumber = 2
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6422),
                            DoctorId = 7,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 7",
                            EpisodeType = "TYPE 1",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6425),
                            SeriesNumber = 2
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6428),
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 8",
                            EpisodeType = "TYPE 3",
                            ModifiedAt = new DateTime(2021, 9, 1, 9, 57, 54, 672, DateTimeKind.Local).AddTicks(6431),
                            SeriesNumber = 2
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeCompanion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanionId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanionId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("EpisodeCompanions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanionId = 1,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanionId = 2,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanionId = 3,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompanionId = 4,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompanionId = 5,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 6,
                            CompanionId = 1,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CompanionId = 2,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 8,
                            CompanionId = 3,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CompanionId = 4,
                            EpisodeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CompanionId = 3,
                            EpisodeId = 3
                        },
                        new
                        {
                            Id = 11,
                            CompanionId = 5,
                            EpisodeId = 4
                        },
                        new
                        {
                            Id = 12,
                            CompanionId = 2,
                            EpisodeId = 4
                        },
                        new
                        {
                            Id = 13,
                            CompanionId = 1,
                            EpisodeId = 5
                        },
                        new
                        {
                            Id = 14,
                            CompanionId = 1,
                            EpisodeId = 6
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeEnemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("EpisodeEnemies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnemyId = 1,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnemyId = 2,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 3,
                            EnemyId = 3,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnemyId = 4,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnemyId = 1,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 6,
                            EnemyId = 2,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 7,
                            EnemyId = 7,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 8,
                            EnemyId = 1,
                            EpisodeId = 3
                        },
                        new
                        {
                            Id = 9,
                            EnemyId = 1,
                            EpisodeId = 4
                        },
                        new
                        {
                            Id = 10,
                            EnemyId = 1,
                            EpisodeId = 5
                        },
                        new
                        {
                            Id = 11,
                            EnemyId = 2,
                            EpisodeId = 5
                        },
                        new
                        {
                            Id = 12,
                            EnemyId = 2,
                            EpisodeId = 6
                        },
                        new
                        {
                            Id = 13,
                            EnemyId = 3,
                            EpisodeId = 6
                        },
                        new
                        {
                            Id = 14,
                            EnemyId = 2,
                            EpisodeId = 7
                        },
                        new
                        {
                            Id = 15,
                            EnemyId = 3,
                            EpisodeId = 7
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodesView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enemies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpisodeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DoctorId");

                    b.ToView("viewEpisodes");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.InformationRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InformationRequests");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Episode", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("DoctorWho.Db.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Author");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeCompanion", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Companion", "Companion")
                        .WithMany()
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companion");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeEnemy", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodesView", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("DoctorWho.Db.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Author");

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
