// <auto-generated />
using System;
using DoctorWho.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoctorWho.Db.Migrations
{
    [DbContext(typeof(DoctorWhoCoreDbContext))]
    [Migration("20210901122852_addCreatedByPropToDbSchemas")]
    partial class addCreatedByPropToDbSchemas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoctorWho.Db.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Suhaib Hamdallah",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 56, DateTimeKind.Local).AddTicks(2577)
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Anas Zakarneh",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(1986)
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mohammad Abu-Qasedo",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(2050)
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Stephen Hillenburg",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(2056)
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Craig McCracken",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(2059)
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Genndy Tartakovsky",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(2063)
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "Alex Hirsch",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(2066)
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Butch Hartman",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 59, DateTimeKind.Local).AddTicks(2069)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Companion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhoPlayed")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Companions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanionName = "Zaid Nour",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(2570)
                        },
                        new
                        {
                            Id = 2,
                            CompanionName = "Jweid Hamdallah",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3196)
                        },
                        new
                        {
                            Id = 3,
                            CompanionName = "Amjad Salhab",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3225)
                        },
                        new
                        {
                            Id = 4,
                            CompanionName = "Osaid Nour",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3229)
                        },
                        new
                        {
                            Id = 5,
                            CompanionName = "Yazan Fouqha",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3232)
                        },
                        new
                        {
                            Id = 6,
                            CompanionName = "Osaid Hamdallah",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3235)
                        },
                        new
                        {
                            Id = 7,
                            CompanionName = "Hasan Khalaf",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3238)
                        },
                        new
                        {
                            Id = 8,
                            CompanionName = "Rayan Hamdallah",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3242)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BithDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DoctorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("FirstEpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. William A. Abdu, M.D, M.S.",
                            DoctorNumber = 1,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(3894)
                        },
                        new
                        {
                            Id = 2,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Myles. B. Abbott, M.D.",
                            DoctorNumber = 2,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(4928)
                        },
                        new
                        {
                            Id = 3,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Khalid Abbed, M.D.",
                            DoctorNumber = 3,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(4980)
                        },
                        new
                        {
                            Id = 4,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Fouad. M. Abbas, M.D.",
                            DoctorNumber = 4,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(4985)
                        },
                        new
                        {
                            Id = 5,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Naresh Trehan",
                            DoctorNumber = 5,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(4988)
                        },
                        new
                        {
                            Id = 6,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Ahmad Assi",
                            DoctorNumber = 6,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(4993)
                        },
                        new
                        {
                            Id = 7,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Laith Sharaqa",
                            DoctorNumber = 7,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(4996)
                        },
                        new
                        {
                            Id = 8,
                            BithDate = new DateTime(1962, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Hamza Nour",
                            DoctorNumber = 8,
                            FirstEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEpisodeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(5000)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1800)
                        .HasColumnType("nvarchar(1800)");

                    b.Property<string>("EnemyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Enemies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Eric Cartman",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(5621)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Vicky",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6397)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Stewie Griffin",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6440)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Maleficent",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6444)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Mr. Pickles ",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6448)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Ahmad Nassar",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6451)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Mohammad Domidi",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6454)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "bla bla",
                            EnemyName = "Ammar Omar",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(6458)
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Episode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EpisodeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1800)
                        .HasColumnType("nvarchar(1800)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 1",
                            EpisodeType = "TYPE 1",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(7202),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 2",
                            EpisodeType = "TYPE 2",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(8973),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 3",
                            EpisodeType = "TYPE 3",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(9054),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 4",
                            EpisodeType = "TYPE 3",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(9059),
                            SeriesNumber = 1
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 5",
                            EpisodeType = "TYPE 2",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(9063),
                            SeriesNumber = 2
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 6,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 6",
                            EpisodeType = "TYPE 1",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(9066),
                            SeriesNumber = 2
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 7",
                            EpisodeType = "TYPE 1",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(9120),
                            SeriesNumber = 2
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeDate = new DateTime(2018, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EpisodeNumber = 1,
                            EpisodeTitle = "TITLE 8",
                            EpisodeType = "TYPE 3",
                            ModifiedAt = new DateTime(2021, 9, 1, 15, 28, 52, 60, DateTimeKind.Local).AddTicks(9125),
                            SeriesNumber = 2
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeCompanion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanionId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanionId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("EpisodeCompanions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanionId = 1,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompanionId = 2,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CompanionId = 3,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CompanionId = 4,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 5,
                            CompanionId = 5,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 6,
                            CompanionId = 1,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CompanionId = 2,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 8,
                            CompanionId = 3,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CompanionId = 4,
                            EpisodeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CompanionId = 3,
                            EpisodeId = 3
                        },
                        new
                        {
                            Id = 11,
                            CompanionId = 5,
                            EpisodeId = 4
                        },
                        new
                        {
                            Id = 12,
                            CompanionId = 2,
                            EpisodeId = 4
                        },
                        new
                        {
                            Id = 13,
                            CompanionId = 1,
                            EpisodeId = 5
                        },
                        new
                        {
                            Id = 14,
                            CompanionId = 1,
                            EpisodeId = 6
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeEnemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnemyId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("EpisodeEnemies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnemyId = 1,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnemyId = 2,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 3,
                            EnemyId = 3,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 4,
                            EnemyId = 4,
                            EpisodeId = 1
                        },
                        new
                        {
                            Id = 5,
                            EnemyId = 1,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 6,
                            EnemyId = 2,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 7,
                            EnemyId = 7,
                            EpisodeId = 2
                        },
                        new
                        {
                            Id = 8,
                            EnemyId = 1,
                            EpisodeId = 3
                        },
                        new
                        {
                            Id = 9,
                            EnemyId = 1,
                            EpisodeId = 4
                        },
                        new
                        {
                            Id = 10,
                            EnemyId = 1,
                            EpisodeId = 5
                        },
                        new
                        {
                            Id = 11,
                            EnemyId = 2,
                            EpisodeId = 5
                        },
                        new
                        {
                            Id = 12,
                            EnemyId = 2,
                            EpisodeId = 6
                        },
                        new
                        {
                            Id = 13,
                            EnemyId = 3,
                            EpisodeId = 6
                        },
                        new
                        {
                            Id = 14,
                            EnemyId = 2,
                            EpisodeId = 7
                        },
                        new
                        {
                            Id = 15,
                            EnemyId = 3,
                            EpisodeId = 7
                        });
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodesView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Companions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enemies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EpisodeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<string>("EpisodeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpisodeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeriesNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DoctorId");

                    b.ToView("viewEpisodes");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.InformationRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InformationRequests");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.Episode", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("DoctorWho.Db.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Author");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeCompanion", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Companion", "Companion")
                        .WithMany()
                        .HasForeignKey("CompanionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Companion");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodeEnemy", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorWho.Db.Models.Episode", "Episode")
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enemy");

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("DoctorWho.Db.Models.EpisodesView", b =>
                {
                    b.HasOne("DoctorWho.Db.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("DoctorWho.Db.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.Navigation("Author");

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
